### ISSUE TITLE
MysqlRestarted will never fire

### ISSUE THREAD

**Issue by ivanovv** [samber/awesome-prometheus-alerts#118]
Looking at this alert
```
  - alert: MysqlRestarted
    expr: mysql_global_status_uptime < 60
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MySQL restarted (instance {{ $labels.instance }})"
      description: "MySQL has just been restarted, less than one minute ago on {{ $labels.instance }}.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```
we need to change either `for` or `expr`, `because mysql_global_status_uptime` is in seconds and it won't stay < 60 for 5 minutes.

I'm very new to Prometheus, and I have these two ideas:
1.
```
    expr: mysql_global_status_uptime < 70
    for: 1m
```
This will fire an alert almost immediately after MySQL restart

2. 
```
    expr: mysql_global_status_uptime < 310
    for: 5m
```

This will fire after 5 minutes.

I personally would rather go with first option, but let me know if I'm mistaken here with anything.
