### ISSUE TITLE
Add Ability to specify `for` section of the configs

### ISSUE THREAD

**Issue by ahmadalli** [samber/awesome-prometheus-alerts#127]
e.g. current `KubernetesPodNotHealthy` alert is this:

```
 - alert: KubernetesPodNotHealthy
    expr: min_over_time(sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"})[1h:]) > 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Kubernetes Pod not healthy (instance {{ $labels.instance }})"
      description: "Pod has been in a non-ready state for longer than an hour.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```

that would send alerts for pods that was failed but are removed now. a better rule would be this:

```
- alert: KubernetesPodNotHealthy
  expr: sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"}) > 0
  for: 1h
  labels:
    severity: critical
  annotations:
    summary: "Kubernetes Pod not healthy"
    description: "Pod has been in a non-ready state for longer than an hour."
```

which requires to set `for` to different value than `5m`
