### ISSUE TITLE
mysql_global_status_slow_queries always be fired

### ISSUE THREAD

**Issue by Ozarklake** [samber/awesome-prometheus-alerts#135]
Since mysql_global_status_slow_queries is a global counter, so once when you generate a slow query then the alert will stay up, I think a better way is to monitor the growth rate

```yaml
      - alert: MysqlSlowQueries
        expr: rate(mysql_global_status_slow_queries[2m]) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "MySQL slow queries (instance {{ $labels.instance }})"
          description: "MySQL server is having some slow queries.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

```

I can provide a PR if needed. thank you
