### ISSUE TITLE
Rule doesn't take account of different scrape frequencies

### ISSUE THREAD

**Issue by nikclayton-dfinity** [samber/awesome-prometheus-alerts#155]
This rule:

https://github.com/samber/awesome-prometheus-alerts/blob/57b7007de4cb2b1c4f6219ca39513543f4349b79/_data/rules.yml#L76-L79

doesn't take account of different scrape frequencies.

This should be parameterised by the `interval` label, e.g.:

```
    expr: prometheus_target_interval_length_seconds{quantile="0.9",interval="10s"} > 12
```

to alert if 90%ile frequency for something that should be scraped every 10s is greater than 12s

**Comment by samber** [comment]
I think there is no good way to track this issue in a generic way. Prometheus won't be able to interpret the interval label as an integer.

Should we compare the 0.9 quantile to the 0.5 quantile ?

**Comment by frittentheke** [comment]
@samber The applied `interval="10s"` is jut a label filter, so it is not about the type (integer). It's simply applying the alert only on those targets with this setting - so it will work. But this only scales to a few distinct values.

Maybe at some point it makes sense to apply some sort of templating to the rules to make them work on a certain environment?
Just like the `$__interval` or `$__rate_interval` variables provided by Grafana nowadays (https://www.robustperception.io/what-range-should-i-use-with-rate, https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/) make the $interval variables in all those dashboards (finally) obsolete and give you the best granularity for any case of scrape interval.

**Comment by mac2000** [comment]
From my understading all this rules are not pretended to be blindly copy pasted and having rule like:

```yml
 - name: Prometheus target scraping slow 
   description: Prometheus has 1 minute scrape interval and some of the scrapes are slower 
   query: 'prometheus_target_interval_length_seconds{quantile="0.9",interval="60s"} > 60' 
   severity: warning 
```

might solve absolutely everything, e.g. just from reading its description and seeing the interval and threshold will allow anyone to tune this values
