### ISSUE TITLE
Rule won't alert when a single cpu load is high

### ISSUE THREAD

**Issue by nikclayton-dfinity** [samber/awesome-prometheus-alerts#156]
This rule:

https://github.com/samber/awesome-prometheus-alerts/blob/57b7007de4cb2b1c4f6219ca39513543f4349b79/_data/rules.yml#L169-L172

won't alert on high CPU load as expected.

It will alert if the last two samples are > 80, and it was to stay that way for the full 5 minutes. If one of the samples is below 80 it won't alert. So you could have spikes in load that last for 5 minutes minus the scrape interval and it will not fire.

You probably want to drop the `for` clause and use 

```
100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
```

In addition, this will only fire if overall CPU usage is high. You might have a situation where you have a multicore machine, one of the cores is pegged (indicating perhaps that a single-threaded program is having problems, or the kernel is not using all CPUs properly).

To catch that you want something like:

```
 - alert: HostHighCoreLoad
    expr: 100 - (avg by(instance, cpu) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    labels:
      severity: warning
    annotations:
      summary: "Host has high load on a single core (instance {{ $labels.instance }})"
      description: "Single core has load > 80%, unbalance workload?\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```
