### ISSUE TITLE
KubernetesJobCompletion will always fire while job is running

### ISSUE THREAD

**Issue by djhoese** [samber/awesome-prometheus-alerts#157]
I could be misunderstanding the purpose of this, but I'm seeing some weird behavior with this rule. The rule is currently defined as:

```
  - alert: KubernetesJobCompletion
    expr: kube_job_spec_completions - kube_job_status_succeeded > 0 or kube_job_status_failed > 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Kubernetes job completion (instance {{ $labels.instance }})"
      description: "Kubernetes Job failed to complete\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```

`kube_job_spec_completions` will always be some number 1 or higher. It is the number of completions configured for the job. It isn't the number of completed pods for the job; that should be `kube_job_complete`. While the job is running the result of the first part of this expression will *always* be true (1 - 0 > 0). So if the job doesn't finish within 5 minutes, this alert will always fire and then get resolved later when the job does succeed.

I *think* this should be changed to `kube_job_complete`, right? Otherwise the rule should be adjusted in the `for:` to be as long as a job could take to succeed (not very accurate or flexible, I think).
