### ISSUE TITLE
Generated rules are not yaml compliant when " embeded in the description

### ISSUE THREAD

**Issue by BarnacleBob** [samber/awesome-prometheus-alerts#159]
If a rule in the _data/rules.yml file has a " in the description such as Host EDAC Correctable Errors detected:
```
              - name: Host EDAC Correctable Errors detected
                description: '{{ $labels.instance }} has had {{ printf "%.0f" $value }} correctable memory errors reported by EDAC in the last 5 minutes.'
                query: 'increase(node_edac_correctable_errors_total[5m]) > 0'
                severity: info
```

the generated yaml isnt valid syntax (this is the copy off the current live site:
```
  - alert: HostEdacCorrectableErrorsDetected
    expr: increase(node_edac_correctable_errors_total[5m]) > 0
    for: 5m
    labels:
      severity: info
    annotations:
      summary: "Host EDAC Correctable Errors detected (instance {{ $labels.instance }})"
      description: "{{ $labels.instance }} has had {{ printf "%.0f" $value }} correctable memory errors reported by EDAC in the last 5 minutes.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```
You will get the error "found character that cannot start any token".  The issue is " inside of the double quoted string is not escaped.  In the data.yml things are in single quoted strings.
