### ISSUE TITLE
EtcdHighNumberOfLeaderChanges: " could not parse expression: 1:48: parse error: missing unit character in duration"

### ISSUE THREAD

**Issue by floek** [samber/awesome-prometheus-alerts#179]
Hi,

rule EtcdHighNumberOfLeaderChanges has a bug. Should be
```yaml
- alert: EtcdHighNumberOfLeaderChanges
  expr: increase(etcd_server_leader_changes_seen_total[10m]) > 2
  for: 0m
  labels:
    severity: warning
  annotations:
    summary: "Etcd high number of leader changes (instance {{ $labels.instance }})"
    description: "Etcd leader changed more than 2 times during 10 minutes\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```

instead of
```yaml
- alert: EtcdHighNumberOfLeaderChanges
  expr: increase(etcd_server_leader_changes_seen_total[10]) > 2
  for: 0m
  labels:
    severity: warning
  annotations:
    summary: "Etcd high number of leader changes (instance {{ $labels.instance }})"
    description: "Etcd leader changed more than 2 times during 10 minutes\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```

Cheers,
floek
