### ISSUE TITLE
optimise up == 0

### ISSUE THREAD

**Issue by Auggie321** [samber/awesome-prometheus-alerts#195]
sir,

About rules.yml's node/app(up == 0) down questions.

check from https://awesome-prometheus-alerts.grep.to/,  

sometimes network not steady,  there would have some packet loss , alertmanger notice app down, up  again and again.

it there have some better way to write rules with some in 1min hit 3, then notice down. 

is't  would be better for those?

some like: 

elasticsearch_cluster_health_up{job="elk_job"} == 0

how to write this would be better , in 1min hit three, then notice down; and recovery how to confirm .

thank you.

**Comment by samber** [comment]
Hi @Auggie321,

I'm not sure to understand your problem.

If you have flapping alerts and would like to trigger a notification only for long downtime, you should check this => https://awesome-prometheus-alerts.grep.to/alertmanager

For example, the following alert won't be triggered for downtime shorter than 3min:

```yaml
 - alert: PrometheusTargetMissing
    expr: up == 0
    for: 3m
    labels:
      severity: critical
    annotations:
      summary: Prometheus target missing (instance {{ $labels.instance }})
      description: A Prometheus target has disappeared. An exporter might be crashed.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}
```
