### ISSUE TITLE
Wrong metric: node_hwmon_temp_alarm

### ISSUE THREAD

**Issue by camelstrike** [samber/awesome-prometheus-alerts#200]
Metric `node_hwmon_temp_alarm` doesn't exist on prometheus and I couldn't find any reference online, the metric that should be used is `node_hwmon_temp_crit_alarm_celsius`

HELP node_hwmon_temp_crit_alarm_celsius Hardware monitor for temperature (crit_alarm)

Example:

```
- alert: HostNodeOvertemperatureAlarm
    expr: node_hwmon_temp_crit_alarm_celsius == 1
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Host node overtemperature alarm (instance {{ $labels.instance }})
      description: Physical node temperature alarm triggered\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}
```
