### ISSUE TITLE
Haproxy alerts make no sense, are duplicated, etc.

### ISSUE THREAD

**Issue by Gui13** [samber/awesome-prometheus-alerts#201]
I'm trying to use the Haproxy alerts, and they make no sense. 

Examples:

<img width="911" alt="image" src="https://user-images.githubusercontent.com/44523/109527004-7e33f100-7ab3-11eb-913a-d904aa9ce262.png">

These two are exactly the same, but they don't share the same description and are confusing.

---

```
  - alert: HaproxyHighHttp4xxErrorRateServer
    expr: sum by (server) rate(haproxy_server_http_responses_total{code="4xx"}[1m]) / sum by (backend) rate(haproxy_server_http_responses_total[1m]) * 100 > 5
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: HAProxy high HTTP 4xx error rate server (instance {{ $labels.instance }})
      description: Too many HTTP requests with status 4xx (> 5%) on server {{ $labels.server }}\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}
```

This is nonsense:  `sum by (server) / sum by (backend)` will have different cardinality so you'll be stuck with no data returned and no alerts whatsoever.

--- 

For the "pre-2.0" exporter, when I click on "copy section", there are metrics that don't exist. Especially:

- `haproxy_backend_active_servers`
- `(sum by (proxy) (rate(haproxy_backend_connection_errors_total[1m])))` # proxy doesn't exist as a label

---

All in all, I love awesome alerts, but this time I got bit and I'm starting to wonder if I should trust this repository.

I'll try to push a PR when I'm finished sorting out the alerts.
