### ISSUE TITLE
Traefik has duplicate sections

### ISSUE THREAD

**Issue by Prof-Bloodstone** [samber/awesome-prometheus-alerts#202]
When looking at Traefik rules <https://awesome-prometheus-alerts.grep.to/rules#traefik>, you'll notice there's 2 sections:
> 3.4. Traefik : Embedded exporter (3 rules)

as well as:

> 3.4. Traefik : Embedded exporter v2 (3 rules)

This isn't too bad, but causes noticeable breakage.
1. Can't link to second section - the link always points to the first one
2. Can't copy specific alert - it always copies given rule from both sections at the same time.
    I.E. copying `Traefik Backend Down` copies also `TraefikServiceDown` and results in:
    ```yaml
        - alert: TraefikBackendDown
	      expr: count(traefik_backend_server_up) by (backend) == 0
	      for: 0m
	      labels:
	        severity: critical
	      annotations:
	        summary: Traefik backend down (instance {{ $labels.instance }})
	        description: All Traefik backends are down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}
	  
	    - alert: TraefikServiceDown
	      expr: count(traefik_service_server_up) by (service) == 0
	      for: 0m
	      labels:
	        severity: critical
	      annotations:
	        summary: Traefik service down (instance {{ $labels.instance }})
	        description: All Traefik services are down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}
	 ```
3. Copying alerts from one section, also copies alerts from the other section.
