### ISSUE TITLE
CoreDNS: Invalid metric name

### ISSUE THREAD

**Issue by milgradesec** [samber/awesome-prometheus-alerts#203]
CoreDNS metric name for panics is `coredns_panics_total` not `coredns_panic_count_total`

New rule with name changed:
```yaml
  - alert: CorednsPanicCount
    expr: increase(coredns_panics_total[1m]) > 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: CoreDNS Panic Count (instance {{ $labels.instance }})
      description: Number of CoreDNS panics encountered\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}
```
