### ISSUE TITLE
Discussion: Increase Function vs. min_over_time

### ISSUE THREAD

**Issue by mstoetzer** [samber/awesome-prometheus-alerts#206]
The following rule is given [Pod Healthy Rule](https://awesome-prometheus-alerts.grep.to/rules.html#rule-kubernetes-16):

```yaml
- alert: KubernetesPodNotHealthy
    expr: min_over_time(sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"})[1h:]) > 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Kubernetes Pod not healthy (instance {{ $labels.instance }})
      description: Pod has been in a non-ready state for longer than an hour.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}
```

What is the advantage of using `min_over_time` compared to `increase` here?
