### ISSUE TITLE
Alert "PostgresqlReplicationLagBytes" cannot be executed

### ISSUE THREAD

**Issue by khaledavarteq** [samber/awesome-prometheus-alerts#212]
The alert `PostgresqlReplicationLagBytes` (see below) cannot be executed by Prometheus. It seems the provided expression is wrong. When trying to evaluate the expression, Prometheus produces the following error message (error message by Prometheus graph):

```
Error executing query: invalid parameter "query": 1:63: parse error: unexpected <GROUP_RIGHT>
```

```yaml
  - alert: PostgresqlReplicationLagBytes
    expr: (pg_xlog_position_bytes and pg_replication_is_replica == 0) - GROUP_RIGHT(instance) (pg_xlog_position_bytes and pg_replication_is_replica == 1) > 1e+09
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Postgresql replication lag bytes (instance {{ $labels.instance }})
      description: Postgres Replication lag (in bytes) is high\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}
```
