### ISSUE TITLE
Alert KubernetesPodNotHealthy reporting incorrect alerts

### ISSUE THREAD

**Issue by mastaab** [samber/awesome-prometheus-alerts#215]
The way the following alert works is (from my understanding), that is any Pod that is "Pending|Unknown|Failed" state for longer than the default resolution in the last hour will trigger the alert. At least that's how the alert is firing for me.
The Alert description says something else, the pod should be down for longer than an hour.

```
  - alert: KubernetesPodNotHealthy
    expr: min_over_time(sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"})[1h:]) > 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Kubernetes Pod not healthy (instance {{ $labels.instance }})
      description: Pod has been in a non-ready state for longer than an hour.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}
```

I'm no expert on PromQL but maybe the range/resolution has to be changed like this: [1h:1h]?
