### ISSUE TITLE
Rule KubernetesOutOfCapacity gives error

### ISSUE THREAD

**Issue by rolfberkenbosch** [samber/awesome-prometheus-alerts#227]
Hi All,

The following rule give the error:
```
many-to-many matching not allowed: matching labels must be unique on one side
```

The code that has been published on the website:
```yaml
  - alert: KubernetesOutOfCapacity
    expr: sum by (node) ((kube_pod_status_phase{phase="Running"} == 1) + on(pod, namespace) group_left(node) (0 * kube_pod_info)) / sum(kube_node_status_allocatable_pods) by (node) * 100 > 90
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Kubernetes out of capacity (instance {{ $labels.instance }})
      description: "{{ $labels.node }} is out of capacity\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
```

Any idea how to fix this ?

**Comment by Tomasz-Kluczkowski** [comment]
Looks like this alert is indeed bugged. Tested in grafana, getting similar error.

```
"found duplicate series for the match group .... on the right hand-side of the operation: ....
many-to-many matching not allowed: matching labels must be unique on one side"
```

**Comment by samber** [comment]
Could you please try to fix this?

I currently have no k8s cluster on my side.

**Comment by Samgarr** [comment]
Hi,
KubernetesOutOfCapacity alert is still broken for me with rule:
```
  - alert: KubernetesOutOfCapacity
    expr: sum by (node) ((kube_pod_status_phase{phase="Running"} == 1) + on(uid) group_left(node) (0 * kube_pod_info{pod_template_hash=""})) / sum by (node) (kube_node_status_allocatable{resource="pods"}) * 100 > 90
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Kubernetes out of capacity (instance {{ $labels.instance }})
      description: "{{ $labels.node }} is out of capacity\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
```
After few tries i fix expresion like this and its working:
```
sum by (node) ((kube_pod_status_phase{phase="Running"} == 1) + on(pod,namespace) group_left(node)
      (0 * kube_pod_info{pod_template_hash=""})) / sum by (node) (kube_node_status_allocatable{resource="pods"})
      * 100
```
