### ISSUE TITLE
host network interface saturated : filter virtual network interfaces and inifinite values

### ISSUE THREAD

**Issue by niko2** [samber/awesome-prometheus-alerts#236]
Hi,

I would suggest to modify "host network interface saturated" alert this way :

* virtual network interface speed is often reported as 10Mbits/s
* label for device name has been fixed with "device" instead of "interface"
* when device speed is unknown (for some virtual machines), result is infinite (+Inf), which generates false-positive alerts

```yaml
            - name: Host Network Interface Saturated
                description: 'The network interface "{{ $labels.device }}" on "{{ $labels.instance }}" is getting overloaded.'
                query: '(rate(node_network_receive_bytes_total{device!~"^tap.*|^vnet.*|^veth.*|^tun.*"}[1m]) + rate(node_network_transmit_bytes_total{device!~"^tap.*|^vnet.*|^veth.*|^tun.*"}[1m])) / node_network_speed_bytes{device!~"^tap.*|^vnet.*|^veth.*|^tun.*"} > 0.8 < 1000'
                severity: warning
                for: 1m
```
