### ISSUE TITLE
Question about "HAProxy HTTP slowing down" alert

### ISSUE THREAD

**Issue by kerossin** [samber/awesome-prometheus-alerts#251]
Hey,

[3.3.1.10. HAProxy HTTP slowing down](https://awesome-prometheus-alerts.grep.to/rules.html#rule-haproxy-1-10) - is this alert only useful for HTTP backends?

The reason I'm asking is because there are metrics that specifically have http in their name and I think this one in the past had it aswell. But currently it seems to return crazy high numbers for TCP mode backends:
{proxy="kubernetes-apiserver"} 28055.263
  
  
Another question about the query itself, should it really be `avg by (proxy)`?
Because 'proxy' = a HAProxy backend so it doesn't measure a whole instance's average request time which I think this is supposed to do. It could also average across several instances if you have backends with the same name on multiple HAProxy instances which would also be confusing and possibly hide an unhealthy instance.

Also, doing `by (X)` drops all other labels so when we do `avg by (proxy)` we then can't use $labels.instance here `summary: HAProxy HTTP slowing down (instance {{ $labels.instance }})`.

Maybe something like this is more correct?
```
  - alert: HaproxyHttpSlowingDown
    expr: avg by (instance) (haproxy_backend_max_total_time_seconds) > 1
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: HAProxy HTTP slowing down (instance {{ $labels.instance }})
      description: "Average request time is increasing - {{ $value | printf \"%.2f\"}}\n"
```
