### ISSUE TITLE
Kubernetes Pod not healthy Alerting too soon

### ISSUE THREAD

**Issue by rubenssoto** [samber/awesome-prometheus-alerts#253]
Hello,

How are you?

I've been using this alert on my prometheus, but the alert is triggered too soon.
```
alert: KubernetesPodNotHealthy
    expr: min_over_time(sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"})[15m:1m]) > 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Kubernetes Pod not healthy (instance {{ $labels.instance }})
      description: "Pod has been in a non-ready state for longer than 15 minutes.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
```

I receive the alert in much less than 15 minutes. Could you help me?
