### ISSUE TITLE
An Alert for MongoDb failed backup

### ISSUE THREAD

**Issue by Thomas-Rice** [samber/awesome-prometheus-alerts#271]
I'm using this in order to run automated backups on my MongoDB instance running on Kubnernetes:
https://github.com/stefanprodan/mgob

I noticed that the current rules do not cover when a backup has failed & the same for any subsequent backups. 

So I have written the rule below. Could you consider adding this to share to others please? 

```
    - alert: FailedBackupCountGreaterThanOne
      expr: mgob_scheduler_backup_total{status="500"} > 0
      for: 5m
      labels:
        severity: error
      annotations:
        summary: "Mongo Database Backup Has Failed"
        description: "At least 1 failed backup has occurred for the Mongo-Protect pod responsible for backing up Mongo"
```
