### ISSUE TITLE
Add alert for too many jenkins plugins which need updating

### ISSUE THREAD

**Issue by corporate-gadfly** [samber/awesome-prometheus-alerts#273]
Thanks in advance, but I'm not sure if I can make a proper pull request, but here is what I use for an alert when too many jenkins plugins need updating _(using [Jenkins Prometheus Metrics Plugin](https://github.com/jenkinsci/prometheus-plugin))_:
```
- alert: JenkinsTooManyPluginsNeedUpate
  expr: sum(jenkins_plugins_withUpdate) by (instance) > 3
  for: 1m
  labels:
    severity: notify
    frequency: daily
  annotations:
    summary: " {{ $labels.instance }} too many plugins updates"
    description: " {{ $labels.instance }} has {{ $value }} plugins that require an update"
```
