### ISSUE TITLE
Add Prometheus alerts for Apache Pulsar 

### ISSUE THREAD

**Issue by mkoertgen** [samber/awesome-prometheus-alerts#285]
We use this Prometheus rules for multiple Apache Pulsar clusters in production

```
    - name: pulsar.rules
      rules:
        - alert: PulsarSubscriptionHighNumberOfBacklogEntries
          expr: sum(pulsar_subscription_back_log) by (subscription) > 5000
          for: 1h
          labels:
            severity: warning
            namespace: pulsar
          annotations:
            summary: Pulsar Subscription High Number Of Backlog Entries (instance {{ $labels.instance }})
            description: "The number of subscription backlog entries is over 5k\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
            dashboard: https://grafana.${domain_name}/d/pulsar-topic-metrics
        - alert: PulsarSubscriptionVeryHighNumberOfBacklogEntries
          expr: sum(pulsar_subscription_back_log) by (subscription) > 100000
          for: 1h
          labels:
            severity: critical
            namespace: pulsar
          annotations:
            summary: Pulsar Subscription Very High Number Of Backlog Entries (instance {{ $labels.instance }})
            description: "The number of subscription backlog entries is over 100k\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
            dashboard: https://grafana.${domain_name}/d/pulsar-topic-metrics
        - alert: PulsarTopicLargeBacklogStorageSize
          expr: sum(pulsar_storage_size > 5*1024*1024*1024) by (topic)
          for: 1h
          labels:
            severity: warning
            namespace: pulsar
          annotations:
            summary: Pulsar Large Backlog Storage Size (instance {{ $labels.instance }})
            description: "The topic backlog storage size is over 5 GB\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
            dashboard: https://grafana.${domain_name}/d/pulsar-topic-metrics
        - alert: PulsarTopicVeryLargeBacklogStorageSize
          expr: sum(pulsar_storage_size > 20*1024*1024*1024) by (topic)
          for: 1h
          labels:
            severity: critical
            namespace: pulsar
          annotations:
            summary: Pulsar Very Large Backlog Storage Size (instance {{ $labels.instance }})
            description: "The topic backlog storage size is over 20 GB\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
            dashboard: https://grafana.${domain_name}/d/pulsar-topic-metrics
        - alert: PulsarHighWriteLatency
          expr: sum(pulsar_storage_write_latency_overflow > 0) by (topic)
          for: 1h
          labels:
            severity: critical
            namespace: pulsar
          annotations:
            summary: Pulsar High Write Latency (instance {{ $labels.instance }})
            description: "Messages cannot be written in a timely fashion\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
            dashboard: https://grafana.${domain_name}/d/pulsar-topic-metrics
        - alert: PulsarLargeEventPayload
          expr: sum(pulsar_entry_size_overflow > 0) by (topic)
          for: 1h
          labels:
            severity: warning
            namespace: pulsar
          annotations:
            summary: Pulsar Large Event Payload (instance {{ $labels.instance }})
            description: "Observing large message payload (> 1MB)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
            dashboard: https://grafana.${domain_name}/d/pulsar-topic-metrics
        - alert: PulsarHighLedgerDiskUsage
          expr: sum(bookie_ledger_dir__pulsar_data_bookkeeper_ledgers_usage) by (kubernetes_pod_name) > 75
          for: 1h
          labels:
            severity: critical
            namespace: pulsar
          annotations:
            summary: Pulsar High Ledger Disk Usage (instance {{ $labels.instance }})
            description: "Observing Ledger Disk Usage (> 75%)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
            dashboard: https://grafana.${domain_name}/d/pulsar-bookie-metrics
        - alert: PulsarReadOnlyBookies
          expr: count(bookie_SERVER_STATUS{} == 0) by (pod)
          for: 5m
          labels:
            severity: critical
            namespace: pulsar
          annotations:
            summary: Pulsar ReadOnly Bookies (instance {{ $labels.instance }})
            description: "Observing Readonly Bookies\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
            dashboard: https://grafana.${domain_name}/d/pulsar-bookie-metrics
        - alert: PulsarHighNumberOfFunctionErrors
          expr: sum((rate(pulsar_function_user_exceptions_total{}[1m]) + rate(pulsar_function_system_exceptions_total{}[1m])) > 10) by (name)
          for: 1m
          labels:
            severity: critical
            namespace: pulsar
          annotations:
            summary: Pulsar High Number Of Function Errors (instance {{ $labels.instance }})
            description: "Observing more than 10 Function errors per minute\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
            dashboard: https://grafana.${domain_name}/d/pulsar-functions-metrics
        - alert: PulsarHighNumberOfSinkErrors
          expr: sum(rate(pulsar_sink_sink_exceptions_total{}[1m]) > 10) by (name)
          for: 1m
          labels:
            severity: critical
            namespace: pulsar
          annotations:
            summary: Pulsar High Number Of Sink Errors (instance {{ $labels.instance }})
            description: "Observing more than 10 Sink errors per minute\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
            dashboard: https://grafana.${domain_name}/d/pulsar-sinks-metrics
```
