### ISSUE TITLE
New: Cloudflare alert rules

### ISSUE THREAD

**Issue by rmalenko** [samber/awesome-prometheus-alerts#306]
```yaml
- name: Cloudflare
  rules:
  - alert: CloudflareHttp5xxErrorRate
    expr: (sum by (zone) (rate(cloudflare_zone_requests_status{status=~"^5.."}[5m])) / on (zone) sum by (zone) (rate(cloudflare_zone_requests_status[5m]))) * 100 > 5
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: Cloudflare high HTTP 5xx error rate (domain {{ $labels.zone }})
      description: "Too many HTTP requests with status 5xx (> 5%)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: CloudflareHttp4xxErrorRate
    expr: (sum by(zone) (rate(cloudflare_zone_requests_status{status=~"^4.."}[30m])) / on (zone) sum by (zone) (rate(cloudflare_zone_requests_status[30m]))) * 100 > 5
    for: 30m
    labels:
      severity: critical
    annotations:
      summary: Cloudflare high HTTP 4xx error rate (domain {{ $labels.zone }})
      description: "Too many HTTP requests with status 4xx (> 5%)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
```
