### ISSUE TITLE
Question around KubernetesCronjobTooLong

### ISSUE THREAD

**Issue by rrey-aviatrix** [samber/awesome-prometheus-alerts#307]
Hi !

I am wondering if these 2 alerts are not context dependent:

```
- alert: KubernetesCronjobTooLong
    expr: time() - kube_cronjob_next_schedule_time > 3600
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Kubernetes CronJob too long (instance {{ $labels.instance }})
      description: "CronJob {{ $labels.namespace }}/{{ $labels.cronjob }} is taking more than 1h to complete.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
  # }}}
```

For `KubernetesCronjobTooLong`, I guess that depending on the cronjob configuration (like once a day), it may be totally legit that next schedule is over 1 hour. 

Or did I missing something ?
