### ISSUE TITLE
Add alerting rule for the metric: node_filesystem_device_error

### ISSUE THREAD

**Issue by gitqlt** [samber/awesome-prometheus-alerts#375]
Monitoring the `node_filesystem_device_error` metric can help with any hardware or network issue.
For example, I've found that it is a good indicator when the password of an NFS or CIFS mount device has expired.
Can also be used to detect other network errors/misconfigurations or hardware failures.

**Comment by samber** [comment]
hi @gitqlt 

If you can give me some promql queries and description, I can add it to the config.

**Comment by gitqlt** [comment]
Hi @samber
I use this alerting rule:

````
rules:
  - alert: Filesystem Device Error
    expr: 'node_filesystem_device_error == 1'
    for: 2m
    labels:
      severity: critical
      from: Node Exporter
    annotations:
      description: Filesystem device error
      summary: '{{ $labels.instance }}: Device error with the {{ $labels.mountpoint }} filesystem'
````
