### ISSUE TITLE
CPU load

### ISSUE THREAD

**Issue by marbetschar** [samber/awesome-prometheus-alerts#38]
I'm currently testing some of your alert rules and stumbled accross the CPU load snippet. I'm not 100% sure how it exactly works, but if I got this straight it should trigger an alert when the average CPU usage for 30mins is greater than 2 ... right?

```
- alert: CpuLoad
  expr: node_load15 / (count without (cpu, mode) (node_cpu_seconds_total{mode="system"})) > 2
  for: 30m
  labels:
    severity: warning
  annotations:
    summary: "CPU load (instance {{ $labels.instance }})"
    description: "CPU load (15m) is high\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```

I ran the `stress` tool yesterday for ~1.5h which pushed CPU usage to 100% within this timespan. During this load test, I executed the following expression as Prometheus query - and the returned value crawled upwards to 1.0, but never completely reached 1.0:

```
node_load15 / (count without (cpu, mode) (node_cpu_seconds_total{mode="system"}))
```

As expected, no alert was triggered. Am I doing something wrong, or is something wrong with the CPU load snippet?

**UPDATE:** I found the following `expr` seems to deliver more accurate results in my case. Not quite sure why one want to track `mode="system"` (as in the your expr) instead of inverting the cpu's `mode="idle"` metric.

```
- alert: CpuLoad
  expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 70
  for: 10m
  labels:
    severity: warning
  annotations:
    summary: "High CPU load (instance {{ $labels.instance }})"
    description: "CPU load is high\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```
