### ISSUE TITLE
Add Prometheus alerts for Kubernetes

### ISSUE THREAD

**Issue by samber** [samber/awesome-prometheus-alerts#4]

**Comment by samber** [comment]
Poke @gaelleiadvize ;)

Looking for contributions ! 🤘 🚀

**Comment by guilhermeblanco** [comment]
Quick ones I use at my clusters. =)

```
  kube-apiserver.alert: |
    groups:
    - name: kube-apiserver.rules
      rules:
      - alert: K8SApiserverDown
        expr: count(up{job="kubernetes-apiservers"} == 0) > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          description: Prometheus failed to scrape API server(s), or all API servers have disappeared from service discovery.
          summary: API server unreachable
      - alert: K8SApiServerLatency
        expr: histogram_quantile(0.99, sum(apiserver_request_latencies_bucket{verb!~"CONNECT|WATCHLIST|WATCH|PROXY"}) WITHOUT (instance, resource)) / 1e+06 > 1
        for: 10m
        labels:
          severity: warning
        annotations:
          description: 99th percentile Latency for {{ $labels.verb }} requests to the kube-apiserver is higher than 1s.
          summary: Kubernetes apiserver latency is high
  kube-controller-manager.alert: |
    groups:
    - name: kube-controller-manager.rules
      rules:
      - alert: K8SControllerManagerDown
        expr: count(up{k8s_app="kube-controller-manager"} == 0) > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          description: There is no running K8S controller manager. Deployments and replication controllers are not making progress.
          summary: Controller manager is down
  kube-scheduler.alert: |
    groups:
    - name: kube-scheduler.rules
      rules:
      - alert: K8SSchedulerDown
        expr: count(up{k8s_app="kube-scheduler"} == 0) > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          description: There is no running K8S scheduler. New pods are not being assigned to nodes.
          summary: Scheduler is down
```
