### ISSUE TITLE
Instance exclusions if virtual/container or just hostname pattern?

### ISSUE THREAD

**Issue by juju4** [samber/awesome-prometheus-alerts#445]
Some rules like HostPhysicalComponentTooHot or HostClockNotSynchronising should exclude virtual machines and containers.
Is this only possible with host pattern?

This does not work for me
```
name: HostPhysicalComponentTooHot
expr: ((node_hwmon_temp_celsius{nodename!~"prefix1*",nodename!~"prefix2*"} * ignoring (label) group_left (instance, job, node, sensor) node_hwmon_sensor_label{label!="tctl",nodename!~"prefix1*",nodename!~"prefix2*"} > 75)) * on (instance) group_left (nodename) node_uname_info{nodename=~".+"}
```

Thanks

**Comment by juju4** [comment]
for now, I silenced alerts at alertmanager level
```
routes:
[...]
    - receiver: "null"
      match:
        alertname: HostOutOfMemory
        nodename: hostname1
      continue: false
```
