### ISSUE TITLE
KubernetesCronjobTooLong detects next scheduled run instead of actual job execution time

### ISSUE THREAD

**Issue by Hellhium** [samber/awesome-prometheus-alerts#465]
## Description
The current `KubernetesCronjobTooLong` alert uses an incorrect expression that triggers based on the time until the next scheduled run, rather than the actual job execution time.

## Current Behavior
```yaml
- alert: KubernetesCronjobTooLong
  expr: "time() - kube_cronjob_next_schedule_time > 3600"
```
This expression triggers when the time until the next scheduled run is more than 1 hour, which is incorrect. It will fire for any CronJob that's scheduled to run more than 1 hour in the future, even if the job itself is running normally.

## Maybe Expected Behavior ?

Here's the corrected expression i currently use:

```yaml
- alert: KubernetesCronjobTooLong
  expr: "kube_job_status_start_time > 0 and absent(kube_job_status_completion_time) and (time() - kube_job_status_start_time) > 3600"
  for: 0m
```

The alert triggers when a job is actively running for more than 1 hour.
