### ISSUE TITLE
CorednsPanicCount

### ISSUE THREAD

**Issue by obeyler** [samber/awesome-prometheus-alerts#51]
I use helm chart: prometheus-9.1.0  (prometheu
the alert rule :
```
- alert: CorednsPanicCount
  expr: increase(coredns_panic_count_total[10min]) > 0
  for: 5m
  labels:
    severity: error
  annotations:
    summary: "CoreDNS Panic Count (instance {{ $labels.instance }})"
    description: "Number of CoreDNS panics encountered\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
``` 
seem to be not correct I see in log :
```

 \"CorednsPanicCount\": could not parse expression: parse error at char 36: bad duration syntax: \"10mi\""
level=error ts=2019-09-13T15:07:29.344Z caller=main.go:757 msg="Failed to apply 
```
something strange it's like 10min become 10mi in log
