### ISSUE TITLE
Add Prometheus alert for openebs

### ISSUE THREAD

**Issue by obeyler** [samber/awesome-prometheus-alerts#55]
for https://openebs.io/

```
- alert: openebs_used_pool_capacity_percent
        expr: (openebs_used_pool_capacity_percent) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "OpenEBS Pool use more than 80 percent of his capacity (instance {{ $labels.instance }})"
          description: "OpenEBS Pool use more than 80% of his capacity\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

```
