### ISSUE TITLE
Context switch rate rule always alerts

### ISSUE THREAD

**Issue by toresbe** [samber/awesome-prometheus-alerts#58]
Hello,

Thanks for your prometheus alerts which are, indeed, well and truly awesome! They've been very helpful in migrating a project away from icinga2 towards prometheus.

There's one alert here that I find will always trigger: The node alert named ContextSwitching. If I plot the graph for the query, I find that idle servers will generally have around 2100 context switches, while a moderately busy one will have 50.5k.

These are generally multi-core processors, does that factor into it at all? Whatever the case, I think there is an issue with the PromQL expression that you might want to be made aware of. Thanks again.

**Comment by paulfantom** [comment]
I was looking quite intensively and couldn't find any backing for an arbitrary number of 1000 used in that alert rule (but bear in mind, this is not an absolute number, but a rate!).

Alerting on a number of context switches by itself without tying it with another metrics is quite pointless (as you already observed in your setup). This is due to the nature of how context switches are "generated" and is heavily dependent on types of applications running as well as a number of cores.

More info: [[1](http://www.linfo.org/context_switch.html)], [[2](http://www.linfo.org/system_call.html)], [[3](https://en.wikipedia.org/wiki/System_call)]

**Comment by toresbe** [comment]
Thanks for the prompt reply. I'm quite familiar with context switches - it seems like it would be useful to generate some alert if there was a huge increase over time, for instance. 

It's here: https://awesome-prometheus-alerts.grep.to/rules#host - 2.11. Context switching

**Comment by paulfantom** [comment]
Yes, it would be useful to alert on huge increase over time and that's what that alert does (alerts on the rate over 5m). The problem is with quantifying "huge" as it will be different for different setups.

**Comment by samber** [comment]
I just added a comment to the alert:

![image](https://user-images.githubusercontent.com/2951285/67622000-dbf85f00-f815-11e9-94cb-7932c41d02ec.png)

**Comment by therist** [comment]
way better to redefine the expression into

(rate(node_context_switches_total[5m]))/(count without(cpu, mode) (node_cpu_seconds_total{mode="idle"}))

This gets context switches, but then divides per core number. Here the number 1000 probably makes more sense.

**Comment by samber** [comment]
@therist oh yes!
I just pushed a fix.

**Comment by toresbe** [comment]
> This gets context switches, but then divides per core number. Here the number 1000 probably makes more sense.

Thank you, that's exactly the sort of thing I was hoping for!

**Comment by ShankaraStefan** [comment]
Should be:

(rate(node_context_switches_total[5m]))/(count without(cpu, **job**) (node_cpu_seconds_total{mode="idle"}))

job instead of mode (mode is already set to be "idle"!)

**Comment by fzyzcjy** [comment]
@toresbe 

> while a moderately busy one will have 50.5k

By the way, I wonder how many cores do you have? I am seeing about 40k context switch on a 4core 16GB machine that has about 50% CPU usage. So I am wondering whether that is too high (I have tried to dig a bit but no clues yet).

**Comment by jerryum** [comment]
I've been measuring the host context switch values for several months - for my case, the new promql gives "average" - 1,500, "std" - 476, "max" - 5,800.   setup 1,800 as a threshold rather than 1,000..... 1,000 still delivers too many meaningless alerts.

**Comment by via-justa** [comment]
If we don't want to hardcode a value, we can compare it to the one-day average and alert when it's 20% (arbitrary) higher than usual.

```yaml
    - alert: NodeContextSwitchingHigh
      expr: |-
        (rate(node_context_switches_total[5m])/count without(mode,cpu) (node_cpu_seconds_total{mode="idle"}))
        /
        (rate(node_context_switches_total[1d])/count without(mode,cpu) (node_cpu_seconds_total{mode="idle"})) > 1.2
      for: 0m
      labels: 
        severity: warning
      annotations:
        summary: Node context switching high (Instance:{{ $labels.instance }})
        description: "CPU core context switching rate is x{{ $labels.value }} than normal at the last 5 minutes."

```

I would recommend creating recording rules for both metrics to reduce the load on the system.

```yaml
    - record: node_context_switches_total:per_core:rate:5m
      expr: rate(node_context_switches_total[5m])/count without(mode,cpu) (node_cpu_seconds_total{mode="idle"})

    - record: node_context_switches_total:per_core:rate:1d
      expr: rate(node_context_switches_total[1d])/count without(mode,cpu) (node_cpu_seconds_total{mode="idle"})

    - alert: NodeContextSwitchingHigh
      expr: node_context_switches_total:per_core:rate:5m / node_context_switches_total:per_core:rate:1d > 1.2
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Node context switching high (Instance:{{ $labels.instance }})
        description: "CPU core context switching rate is x{{ $labels.value }} than normal at the last 5 minutes."
```
