### ISSUE TITLE
Add Elastic Search Alert - Disk Usage

### ISSUE THREAD

**Issue by ebini** [samber/awesome-prometheus-alerts#89]
Hi,

an idea to add for elastic search:

```
    - alert: ElasticsearchDiskUsageTooHigh
      expr: ( 1-(elasticsearch_filesystem_data_available_bytes{}/elasticsearch_filesystem_data_size_bytes{}) ) * 100 > 90
      for: 5m
      labels:
        severity: error
      annotations:
        summary: "Elasticsearch Disk Usage Too High (instance {{ $labels.instance }})"
        description: "The disk usage is over 90% for 5m\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```

```
    - alert: ElasticsearchDiskUsageWarning
      expr: ( 1-(elasticsearch_filesystem_data_available_bytes{}/elasticsearch_filesystem_data_size_bytes{}) ) * 100 > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Elasticsearch Disk Usage warning (instance {{ $labels.instance }})"
        description: "The disk usage is over 80% for 5m\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```
