### ISSUE TITLE
KubernetesPodNotHealthy expr problem

### ISSUE THREAD

**Issue by youpai** [samber/awesome-prometheus-alerts#94]
```
- alert: KubernetesPodNotHealthy
    expr: min_over_time(sum by (namespace, pod, env, stage) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"})[1h]) > 0
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "Kubernetes Pod not healthy (instance {{ $labels.instance }})"
      description: "Pod has been in a non-ready state for longer than an hour.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```

I want to use this ,but the "expr" Doesn't seem right. I get the error like:
```
Error executing query: invalid parameter 'query': 1:107: parse error: ranges only allowed for vector selectors
```
if I use `min_over_time(sum by (namespace, pod, env, stage) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"})[1h:])` , the result is OK。
