### ISSUE TITLE
Add a "for" clause to each alert

### ISSUE THREAD

**Issue by samber** [samber/awesome-prometheus-alerts#96]
Today, we add `for: 5m` to alerts, automatically.

Use case: `mysql_global_status_uptime < 60` would never trigger

`5m` can be the default value.

### Progression:

**Basic resource monitoring**

- [x] Prometheus self-monitoring
- [x] Host/Hardware
- [x] Docker Containers
- [x] Blackbox
- [x] Windows

**Databases and brokers**

- [x] MySQL
- [x] PostgreSQL
- [x] PGBouncer
- [x] Redis
- [x] MongoDB
- [x] RabbitMQ
- [x] Elasticsearch
- [x] Cassandra
- [x] Zookeeper
- [x] Kafka

**Reverse proxies and load balancers**

- [x] Nginx
- [x] Apache
- [x] HaProxy
- [x] Traefik

**Runtimes**

- [x] PHP-FPM
- [x] JVM
- [x] Sidekiq

**Orchestrators**

- [x] Kubernetes
- [x] Nomad
- [x] Consul
- [x] Etcd
- [x] Linkerd
- [x] Istio

**Network and storage**

- [x] Ceph
- [x] ZFS
- [x] OpenEBS
- [x] Minio
- [x] Juniper
- [x] CoreDNS

**Other**

- [x] Thanos

**Comment by nikclayton-dfinity** [comment]
Auto-adding a `for` clause, and assuming that it's relevant for each alert, means that the alerts do not do what you think they do.

Consider

```
  - alert: HostUnusualNetworkThroughputIn
    expr: sum by (instance) (irate(node_network_receive_bytes_total[2m])) / 1024 / 1024 > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host unusual network throughput in (instance {{ $labels.instance }})"
      description: "Host network interfaces are probably receiving too much data (> 100 MB/s)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```

This is supposed to detect sudden spikes where traffic jumps by more than 100MiB over the course of two minutes.

Suppose traffic is at 50MiB, and suddenly jumps to 200MiB.

But the `for` clause means those spikes have to repeat for 5m, meaning that the total increase that you're alerting on is *not* `...bytes_total / 1024 / 1024 > 100`. If a spike happens, and then doesn't repeat within that 5 minute window the alert won't fire.

Similarly, if there's a sharp increase in throughput, and then the throughput remains at the new high level this alert won't fire.

There's another problem -- the use of irate means that this will only fire if the traffic increases within the scrape-interval period.

Suppose the scrape interval is 10s. If the traffic smoothly increases from 50MiB to 200MiB over 60 seconds, you'll see an increase of ~ 22MiB per scrape interval. irate() will look at the last two samples, see an increase of less than 100 MiB, and the alert won't fire.
