### ISSUE TITLE
HostUnusualDiskReadLatency 

### ISSUE THREAD

**Issue by zou2699** [samber/awesome-prometheus-alerts#99]
Hello，I do not understand why use time divided by total ？

```yaml
  - alert: HostUnusualDiskReadLatency
    expr: rate(node_disk_read_time_seconds_total[1m]) / rate(node_disk_reads_completed_total[1m]) > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host unusual disk read latency (instance {{ $labels.instance }})"
      description: "Disk latency is growing (read operations > 100ms)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```
